//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ShiftreportLib
{


    public partial class promoters_mst
    {
        [Key]
        public Nullable<int> promoters_userid { get; set; }
        public string promoter_name { get; set; }
        public string create_userid { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modified_userid { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public string Promoter_Address1 { get; set; }
        public string Promoter_Address2 { get; set; }
        public string Promoter_City { get; set; }
        public string Promoter_State { get; set; }
        public string Promoter_Zip { get; set; }
        public string Promoter_Country { get; set; }
        public Nullable<int> Corp_ID { get; set; }
        public Nullable<int> Store_ID { get; set; }
        public Nullable<int> PayoutMethodId { get; set; }
    }
}
