//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ShiftreportLib
{

 
    
    public partial class vc_coupon_code_mst
    {
        public Nullable<System.DateTime> create_dt { get; set; }
        public string create_usrid { get; set; }
        public string create_userid { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modified_userid { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        [Key]
        public int Coupon_Code_ID { get; set; }
        public Nullable<int> Code_Type { get; set; }
        public bool Code_Redeemed { get; set; }
        public Nullable<System.DateTime> Coupon_Code_Expire_Date { get; set; }
        public Nullable<int> promoter_userid { get; set; }
        public double Promoter_business_Sales_Commision_Rate { get; set; }
        public double Promoter_business_Commission_Sign_Up_Amt { get; set; }
        public double Promoter_customer_Sales_Commision_Rate { get; set; }
        public double Promoter_customer_Commission_Sign_Up_Amt { get; set; }
        public double SignUP_VenueCash_Credit_Amt { get; set; }
        public Nullable<int> SignUP_VenueCash_Credit_Corp_ID_Issued { get; set; }
        public double VenueCash_Credit_Amt { get; set; }
        public Nullable<int> VenueCash_Credit_Corp_ID_Issued { get; set; }
        public double SignUP_VC_Credit_Issued_by_VenueCash_Amt { get; set; }
        public Nullable<int> SignUP_VC_Credit_Issued_by_VenueCash_Corp_ID { get; set; }
        public double SignUP_AC_Credit_Issued_by_VenueCash_Amt { get; set; }
        public Nullable<int> SignUP_VC_Credit_Issued_by_VenueCash_Store_ID { get; set; }
        public double VC_Credit_Issued_by_VenueCash_Amt { get; set; }
        public Nullable<int> VC_Credit_Issued_by_VenueCash_Corp_ID { get; set; }
        public double AC_Credit_Issued_by_VenueCash_Amt { get; set; }
        public Nullable<int> VC_Credit_Issued_by_VenueCash_Store_ID { get; set; }
        public string Coupon_Promotion_Name { get; set; }
        public Nullable<System.DateTime> Coupon_Code_Start_Date { get; set; }
    }
}
